version: '3.9'
services:
  db:
    image: postgres
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SY2Z74RzUx8Afs6d
  api:
    build: ./API
    ports:
      - 5000:8080
    depends_on:
      - db
    volumes:
      - gradle_cache:/app/.gradle
      - dep_cache:/root/.gradle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  client:
    build: ./Client
    ports:
      - 4000:3000
    depends_on:
      - api
    volumes:
      - ./Client/eshop/src:/app/src
      - ./Client/eshop/public:/app/public
      - node_modules:/app/node_modules
volumes:
  gradle_cache:
  dep_cache:
  node_modules:
