/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AddProductToCartDto,
    AddProductToCartDtoFromJSON,
    AddProductToCartDtoToJSON,
    CartDto,
    CartDtoFromJSON,
    CartDtoToJSON,
    ChangeQuantityDto,
    ChangeQuantityDtoFromJSON,
    ChangeQuantityDtoToJSON,
} from '../models';

export interface AddProductToCartRequest {
    addProductToCartDto: AddProductToCartDto;
}

export interface ChangeQuantityRequest {
    changeQuantityDto: ChangeQuantityDto;
}

export interface RemoveProductFromCartRequest {
    productId: string;
}

/**
 * 
 */
export class CheckoutApi extends runtime.BaseAPI {

    /**
     * Add product to cart
     * Add product to cart
     */
    async addProductToCartRaw(requestParameters: AddProductToCartRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        if (requestParameters.addProductToCartDto === null || requestParameters.addProductToCartDto === undefined) {
            throw new runtime.RequiredError('addProductToCartDto','Required parameter requestParameters.addProductToCartDto was null or undefined when calling addProductToCart.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/addProductToCart`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddProductToCartDtoToJSON(requestParameters.addProductToCartDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Add product to cart
     * Add product to cart
     */
    async addProductToCart(requestParameters: AddProductToCartRequest, initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.addProductToCartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change quantity
     * Change quantity
     */
    async changeQuantityRaw(requestParameters: ChangeQuantityRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        if (requestParameters.changeQuantityDto === null || requestParameters.changeQuantityDto === undefined) {
            throw new runtime.RequiredError('changeQuantityDto','Required parameter requestParameters.changeQuantityDto was null or undefined when calling changeQuantity.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/changeQuantity`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeQuantityDtoToJSON(requestParameters.changeQuantityDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Change quantity
     * Change quantity
     */
    async changeQuantity(requestParameters: ChangeQuantityRequest, initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.changeQuantityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create cart
     * Create cart
     */
    async createCartRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/createCart`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Create cart
     * Create cart
     */
    async createCart(initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.createCartRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get cart
     * Get cart
     */
    async getCartRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/getCart`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Get cart
     * Get cart
     */
    async getCart(initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.getCartRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user orders
     * Get user orders
     */
    async getUserOrdersRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/getUserOrders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get user orders
     * Get user orders
     */
    async getUserOrders(initOverrides?: RequestInit): Promise<object> {
        const response = await this.getUserOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Post order
     * Post order
     */
    async postOrderRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/postOrder`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Post order
     * Post order
     */
    async postOrder(initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.postOrderRaw(initOverrides);
        return await response.value();
    }

    /**
     * Remove product form cart
     * Remove product from cart
     */
    async removeProductFromCartRaw(requestParameters: RemoveProductFromCartRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CartDto>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling removeProductFromCart.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/checkout/removeProductFromCart/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartDtoFromJSON(jsonValue));
    }

    /**
     * Remove product form cart
     * Remove product from cart
     */
    async removeProductFromCart(requestParameters: RemoveProductFromCartRequest, initOverrides?: RequestInit): Promise<CartDto> {
        const response = await this.removeProductFromCartRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
