/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductDto,
    ProductDtoFromJSON,
    ProductDtoFromJSONTyped,
    ProductDtoToJSON,
} from './ProductDto';

/**
 * 
 * @export
 * @interface CartProductDto
 */
export interface CartProductDto {
    /**
     * 
     * @type {ProductDto}
     * @memberof CartProductDto
     */
    product?: ProductDto;
    /**
     * 
     * @type {number}
     * @memberof CartProductDto
     */
    quantity?: number;
}

export function CartProductDtoFromJSON(json: any): CartProductDto {
    return CartProductDtoFromJSONTyped(json, false);
}

export function CartProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartProductDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : ProductDtoFromJSON(json['product']),
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function CartProductDtoToJSON(value?: CartProductDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': ProductDtoToJSON(value.product),
        'quantity': value.quantity,
    };
}

