/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CartProductDto,
    CartProductDtoFromJSON,
    CartProductDtoFromJSONTyped,
    CartProductDtoToJSON,
} from './CartProductDto';

/**
 * 
 * @export
 * @interface CartDto
 */
export interface CartDto {
    /**
     * 
     * @type {string}
     * @memberof CartDto
     */
    id?: string;
    /**
     * 
     * @type {Array<CartProductDto>}
     * @memberof CartDto
     */
    products?: Array<CartProductDto>;
    /**
     * 
     * @type {string}
     * @memberof CartDto
     */
    state?: CartDtoStateEnum;
}

/**
* @export
* @enum {string}
*/
export enum CartDtoStateEnum {
    New = 'NEW',
    Ordered = 'ORDERED'
}

export function CartDtoFromJSON(json: any): CartDto {
    return CartDtoFromJSONTyped(json, false);
}

export function CartDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(CartProductDtoFromJSON)),
        'state': !exists(json, 'state') ? undefined : json['state'],
    };
}

export function CartDtoToJSON(value?: CartDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(CartProductDtoToJSON)),
        'state': value.state,
    };
}

