/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeQuantityDto
 */
export interface ChangeQuantityDto {
    /**
     * 
     * @type {string}
     * @memberof ChangeQuantityDto
     */
    productId?: string;
    /**
     * 
     * @type {number}
     * @memberof ChangeQuantityDto
     */
    quantity?: number;
}

export function ChangeQuantityDtoFromJSON(json: any): ChangeQuantityDto {
    return ChangeQuantityDtoFromJSONTyped(json, false);
}

export function ChangeQuantityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeQuantityDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function ChangeQuantityDtoToJSON(value?: ChangeQuantityDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'quantity': value.quantity,
    };
}

