/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductDto
     */
    price?: number;
}

export function CreateProductDtoFromJSON(json: any): CreateProductDto {
    return CreateProductDtoFromJSONTyped(json, false);
}

export function CreateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'price': !exists(json, 'price') ? undefined : json['price'],
    };
}

export function CreateProductDtoToJSON(value?: CreateProductDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'imageUrl': value.imageUrl,
        'price': value.price,
    };
}

